server:
  port: 8088
spring:
  datasource:
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.184.228:3306/wzsjlw?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    druid:
      # 初始化大小
      initial-size: 1
      # 最小
      min-idle: 3
      # 最大
      max-active: 20
      # 连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空连接
      timeBetweenEvictionRunsMillis: 60000
      # 连接池中最小的生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache,并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: stat
mybatis:
  check-config-location: true
  # 配置 JAVA 类型包
  type-aliases-package: com.wzsjlw.site.entity
  # 注册 XML 映射器
  mapper-locations: mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
